Path=/Path/LD_Score
download=/Path/Download
feature="AS_nonAS.enhancer.AS AS_nonAS.enhancer.nonAS AS_nonAS.promoter.AS AS_nonAS.promoter.nonAS chromHMM.E10 chromHMM.E11 chromHMM.E12 chromHMM.E1 chromHMM.E4 chromHMM.E5 chromHMM.enhancer.enhancer chromHMM.promoter.promoter DeepGCF.enhancer.highD_highP DeepGCF.promoter.highD_highP"
Trait="PASS_Alzheimers_Jansen2019 PASS_AlzheimersMaternal_Marioni2018 PASS_AlzheimersPaternal_Marioni2018 PASS_BreastCancer PASS_Crohns_Disease PASS_LDL PASS_ProstateCancer PASS_Triglycerides PASS_Schizophrenia PASS_Type_2_Diabetes UKB_460K.cancer_ALL UKB.Sitting_height_20015_irnt.ldsc.imputed_v3.both_sexes.tsv UKB.Standing_height_50_irnt.ldsc.imputed_v3.both_sexes.tsv UKB.Menarche_2714.ldsc.imputed_v3.both_sexes.tsv UKB.LDL_30780_irnt.ldsc.imputed_v3.both_sexes.tsv UKB.Glucose_30740_irnt.ldsc.imputed_v3.both_sexes.tsv UKB.Cholesterol_30690_irnt.ldsc.imputed_v3.both_sexes.tsv UKB.BMI_23104_irnt.ldsc.imputed_v3.both_sexes.tsv UKB.Blood_pressure_6150_4.ldsc.imputed_v3.both_sexes.tsv UKB.Weight_23098_irnt.ldsc.imputed_v3.both_sexes.tsv"


#01. annotation file
##make annotation
for i in {1..22}; do for j in ${feature};do for k in hg38 pig2hg38;do python3 /Path/Tools/ldsc/make_annot.py --bed-file ${Path}/AnnotationFile/${k}/LDSC.${k}.${j}.bed --bimfile ${download}/1000G_EUR_Phase3_plink/1000G.EUR.QC.${i}.bim --annot-file ${Path}/AnnotationFile/${k}/annot.gz/chr${i}.${j}.annot.gz;done;done;done 
##merge.annot.gz by chr
for i in {1..22}; do for k in hg38 pig2hg38;do for j in ${feature};do gunzip ${Path}/AnnotationFile/${k}/annot.gz/chr${i}.${j}.annot.gz;done;done;done
for i in {1..22};do for k in hg38 pig2hg38; do awk '{print$1"\t"$4"\t"$2"\t"$3}' ${download}/1000G_EUR_Phase3_plink/1000G.EUR.QC.${i}.bim|awk 'BEGIN{print"CHR"}{print$0}' -|paste - ${Path}/AnnotationFile/${k}/annot.gz/chr${i}.AS_nonAS.enhancer.AS.annot ${Path}/AnnotationFile/${k}/annot.gz/chr${i}.AS_nonAS.enhancer.nonAS.annot ${Path}/AnnotationFile/${k}/annot.gz/chr${i}.AS_nonAS.promoter.AS.annot ${Path}/AnnotationFile/${k}/annot.gz/chr${i}.AS_nonAS.promoter.nonAS.annot ${Path}/AnnotationFile/${k}/annot.gz/chr${i}.chromHMM.E10.annot ${Path}/AnnotationFile/${k}/annot.gz/chr${i}.chromHMM.E11.annot ${Path}/AnnotationFile/${k}/annot.gz/chr${i}.chromHMM.E12.annot ${Path}/AnnotationFile/${k}/annot.gz/chr${i}.chromHMM.E1.annot ${Path}/AnnotationFile/${k}/annot.gz/chr${i}.chromHMM.E4.annot ${Path}/AnnotationFile/${k}/annot.gz/chr${i}.chromHMM.E5.annot ${Path}/AnnotationFile/${k}/annot.gz/chr${i}.chromHMM.enhancer.enhancer.annot ${Path}/AnnotationFile/${k}/annot.gz/chr${i}.chromHMM.promoter.promoter.annot ${Path}/AnnotationFile/${k}/annot.gz/chr${i}.DeepGCF.enhancer.highD_highP.annot ${Path}/AnnotationFile/${k}/annot.gz/chr${i}.DeepGCF.promoter.highD_highP.annot |grep -v "ANNOT"|awk 'BEGIN{print"CHR\tBP\tSNP\tCM\tAS_nonAS.enhancer.AS\tAS_nonAS.enhancer.nonAS\tAS_nonAS.promoter.AS\tAS_nonAS.promoter.nonAS\tchromHMM.E10\tchromHMM.E11\tchromHMM.E12\tchromHMM.E1\tchromHMM.E4\tchromHMM.E5\tchromHMM.enhancer.enhancer\tchromHMM.promoter.promoter\tDeepGCF.enhancer.highD_highP\tDeepGCF.promoter.highD_highP"}{print$0}' -|gzip - > ${Path}/AnnotationFile/${k}/ldscore.gz/${k}.all-feature.${i}.annot.gz;done;done 

#02. Computing LD scores with an annot file
for i in {1..22};do for k in hg38 pig2hg38;do python3 /Path/Tools/polyfun/ldsc.py --l2 --bfile ${download}/1000G_EUR_Phase3_plink/1000G.EUR.QC.${i} --ld-wind-cm 1 --annot ${Path}/AnnotationFile/${k}/ldscore.gz/${k}.all-feature.${i}.annot.gz --out ${Path}/AnnotationFile/${k}/ldscore.gz/${k}.all-feature.${i};done;done

##04. Computing Partitioned Heritability by Polyfun
for k in hg38 pig2hg38;do for t in ${Trait};do python3 /Path/Tools/polyfun/ldsc.py --h2 /Path/LD_Score/Trait_sumstats/${t}.formal.sumstats.gz --ref-ld-chr ${Path}/AnnotationFile/${k}/ldscore.gz/${k}.all-feature. --w-ld-chr ${download}/1000G_Phase3_weights_hm3_no_MHC/weights.hm3_noMHC. --frqfile-chr ${download}/1000G_Phase3_frq/1000G.EUR.QC. --overlap-annot --out ${Path}/polyfun.Partitioned_Heritability/${k}/${k}.${t}.polyfun;done;done